### ISSUE TITLE
Improve memory management of SMC functions

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/BayesMallows#112]
- [x] Declare more unchangeable objects as `const` (PR #169)
- [x] Declare aliases as `&` references (PR #169)
- [x] Replace `Rcpp::setdiff()` with `arma_setdiff()` (from misc.cpp) where convenient (PR #170)
- [x] Improve objects that are converted between Rcpp, Armadillo and C++ (several intermediate objects are created, which bloats the functions with multiple copies of essentially the same object)

**Comment by wleoncio** [comment]
Resolved by PR #173
